config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :cocktails
  resources :ingredients do
    collection do
      post 'search'
    end
  end


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :ingredient
end

app/models/favourite.rb
class Favourite < ApplicationRecord
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :user
  belongs_to :cocktail
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :ingredient
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  def index
    if params[:query].present?
      @cocktails = Cocktail.where("name ILIKE ?", "%#{params[:query]}%")
    else
      @cocktails = Cocktail.all
    end
  end


  def show
    @cocktail = Cocktail.find(params[:id])

  end

end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController

  def index
    @favourites = Favourite.where(user: current_user)
  end

  def create
    @favourite = Favourite.new
    @favourite.user = current_user
    @cocktail = Cocktail.find(params[:cocktail_id])
    @cocktail.pub = @cocktail
    if @favourite.save
      redirect_to cocktail_path(@cocktail), notice: "This cocktail was sucesfully added to your favourites"
    end
  end

  def destroy
    @favourite = Favourite.find(params[:id])
    if @favourite.destroy!
      redirect_to user_favourites_path(:user_id), status: :see_other
    else
      render :index, status: :unprocessable_entity
    end
  end

  private

  def favourite_params
    params.require(:favourite).permit(:cocktail_id)
  end

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController



  def show
    @ingredients = Ingredient.where("name LIKE ?", "%#{params[:query]}%")
  end

  def index
    if params[:query].present?
      @ingredients = Ingredient.where("name LIKE ?", "%#{params[:query]}%")
    else
      @ingredients = Ingredient.all
    end


  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cocktails/index.html.erb
<h2>Cocktails</h2>

<div class="container">
  <div class="searchbar">
    <%= form_with url: cocktails_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Search cocktails..."
      %>
      <%= submit_tag "GO!", class: "btn-search" %>
    <% end %>
  </div>

<br>

  <% @cocktails.each do |cocktail| %>
      <%= link_to cocktail_path(cocktail), class: "cocktail" do %>
        <div class="name">
          <%= cocktail.name %>
        </div>
          <%= image_tag(cocktail.strDrinkThumb, class: "cocktail-image") %></ul>
        <div class="ingredients">
          <ul><%= cocktail.strIngredient1.capitalize %></ul>
          <ul><%= cocktail.strIngredient2.capitalize %></ul>
          <ul><%= cocktail.strIngredient3.capitalize %></ul>
        </div>
        <% end %>
  <% end %>

</div>

app/views/cocktails/show.html.erb
<div class="container">

  <h2><%= @cocktail.name %></h2 >

  <div class="cocktail-show">
  <br>
    <%= image_tag(@cocktail.strDrinkThumb, class: "cocktail-image") %></ul>
      <div class="ingredients-show">
        <h4>Ingredients</h4>
        <div class ="list"></div>
          <ul><%= @cocktail.strIngredient1.capitalize %> - <%= @cocktail.strMeasure1 %></ul>
          <ul><%= @cocktail.strIngredient2.capitalize %> - <%= @cocktail.strMeasure2 %></ul>
          <% if @cocktail.strIngredient3? %>
            <ul><%= @cocktail.strIngredient3.capitalize %> - <%= @cocktail.strMeasure3 %></ul>
          <% end %>
          <% if @cocktail.strIngredient4? %>
            <ul><%= @cocktail.strIngredient4.capitalize %> - <%= @cocktail.strMeasure4 %></ul>
          <% end %>
          <% if @cocktail.strIngredient5? %>
            <ul><%= @cocktail.strIngredient5.capitalize %> - <%= @cocktail.strMeasure5 %></ul>
          <% end %>
          <% if @cocktail.strIngredient6? %>
            <ul><%= @cocktail.strIngredient6.capitalize %> - <%= @cocktail.strMeasure6 %></ul>
          <% end %>
          <% if @cocktail.strIngredient7? %>
            <ul><%= @cocktail.strIngredient7.capitalize %> - <%= @cocktail.strMeasure7 %></ul>
          <% end %>
          <% if @cocktail.strIngredient8? %>
            <ul><%= @cocktail.strIngredient8.capitalize %> - <%= @cocktail.strMeasure8 %></ul>
          <% end %>
          <% if @cocktail.strIngredient9? %>
            <ul><%= @cocktail.strIngredient9.capitalize %> - <%= @cocktail.strMeasure9 %></ul>
          <% end %>
        <h4>Direction</h4>
        <%= @cocktail.recipe %>

      </div>
  </div>
</div>

app/views/ingredients/_list.html.erb
<tbody id="ingredients">
  <% @ingredients.each do |ingredient| %>
    <tr>
      <td><%= ingredient.name %></td>
      <td><%= link_to 'Add', edit_ingredient_path(ingredient) %></td>
      <td><%= link_to 'Remove', ingredient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</tbody>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LiquidKitchen</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%# <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

  </head>

  <body><%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
   <div class="row">
     <div class="col-12" id="home">
       <%= image_tag("Cocktail_logo_test.png", width: '300px', height: 'auto') %>
       <h1>Liquid Kitchen</h1>
       <p>The app that find you the cocktails you can make</p>
       <%= button_to "Mix!", "cocktails", :class => "btn-main", :method => :get  %>
       <%# <button class="btn-main" link_to cocktails_path>Mix!</button> %>
     </div>
   </div>

</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="container-footer">
  <%= link_to '/' do %>
    <p class ="icon fa-solid fa-house"></p>
  <% end %>
  <p class="icon fa-solid fa-star"></p>
  <%= link_to 'cocktails' do %>
    <p class ="icon fa-solid fa-martini-glass-citrus"></p>
  <% end %>
  <p class ="icon fa-solid fa-magnifying-glass"></p>
  <p class="icon fa-solid fa-user"></p>
</div>

app/views/shared/_navbar.html.erb
<div class="container-navbar">
  <div class="navbar-name">
    Liquid Kitchen
  </div>
</div>